name: Deploy iOS

on:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: sleep 1m

      - name: Create some new file
        run: echo "text" > "$(shuf -i 10000-99999 -n 1).txt"
        
      - run: git add .

      - name: Setup git
        run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" && git config --global user.name "github-actions[bot]" && git config --global pull.rebase true

      - name: Commit bump version
        run: git commit -a -m "add new file"
      
      - run: git pull origin ${{ github.head_ref }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
